### ISSUE TITLE
Reduce false positives in parking garage icon hits

### ISSUE THREAD

**Issue by tschaub** [planetfederal/sfpark.org#2]
Currently, the parking garage icons are 54x60 pixel graphics.  When the user hovers anywhere in a 54x60 neighborhood around a parking garage, we display a popup for that garage.  This is particularly misleading when you mouse over below a garage (on a blockface that is ~30 pixels away).

**Comment by tschaub** [comment]
Our alternatives here are to use a vector layer with a smaller graphic and appropriate offsets or to convert the graphic to SVG and use displacement in the SLD.

**Comment by dcorliss** [comment]
We found the garage icons sometimes difficult to click on - perhaps the SVG graphic would help this issue as well.

**Comment by bartvde** [comment]
Okay, we have switched to a client-side vector layer, so this should not be an issue anymore.
