### ISSUE TITLE
Scrolling of map when large popup appears is jerky

### ISSUE THREAD

**Issue by dcorliss** [planetfederal/sfpark.org#21]
When pop-up box requires the map to move, the map does a kind of nervous up-and-down shaking in Firefox 4.0.1.  

We turned off Google's animated zooming for other SFpark pages - is this an issue here?  Scrolling should be smoother.

**Comment by bartvde** [comment]
Probably best to just upgrade OpenLayers and gxp so we move to GoogleNG instead. That should fix this issue and improve the panning experience as well.

**Comment by bartvde** [comment]
That does not seem to help a lot though, so maybe we should just turn off animated panning.
