### ISSUE TITLE
Pop up data formatted as tables with alt row bg color

### ISSUE THREAD

**Issue by dcorliss** [planetfederal/sfpark.org#25]
Pop-up boxes should show up as formatted tables, like the SFpark iPhone app.

**Comment by bartvde** [comment]
Donovan, can you deliver to us the HTML/css markup used by the iphone application for the tables?

**Comment by bartvde** [comment]
Header Background: #5D5D5D
Row Background: #EFEFEF
Table Border: #CCCCCC
